
var data0 = [
{groupId: "0", id: "bd_n", nm: "bd_n", ct: "bd", si: "n", dw: 18, cap: 224, count: 15, co: 0.24, },
{groupId: "0", id: "bd_1", nm: "bd_1", ct: "bd", si: "1", dw: 23, cap: 374, count: 258, co: 0.18, },
{groupId: "0", id: "bd_3", nm: "bd_3", ct: "bd", si: "3", dw: 25, cap: 508, count: 456, co: 0.23, },
{groupId: "0", id: "bd_4", nm: "bd_4", ct: "bd", si: "4", dw: 27, cap: 439, count: 27, co: NaN, },
{groupId: "0", id: "bd_5", nm: "bd_5", ct: "bd", si: "5", dw: 31, cap: 528, count: 84, co: NaN, },
{groupId: "0", id: "bd_6", nm: "bd_6", ct: "bd", si: "6", dw: 38, cap: 510, count: 470, co: 0.33, },
{groupId: "0", id: "cpu_4t", nm: "cpu_4t", ct: "cpu", si: "4t", dw: 34, cap: 353, count: 69, co: NaN, },
{groupId: "0", id: "cpu_5t", nm: "cpu_5t", ct: "cpu", si: "5t", dw: 34, cap: 563, count: 3, co: NaN, },
{groupId: "0", id: "cpu_cl", nm: "cpu_cl", ct: "cpu", si: "cl", dw: 54, cap: 662, count: 20, co: NaN, },
{groupId: "0", id: "cpu_cxl", nm: "cpu_cxl", ct: "cpu", si: "cxl", dw: 51, cap: 734, count: 18, co: NaN, },
{groupId: "0", id: "br_m", nm: "br_m", ct: "br", si: "m", dw: 141, cap: 1056, count: 12644, co: 1.24, },
{groupId: "0", id: "br_l", nm: "br_l", ct: "br", si: "l", dw: 178, cap: 1415, count: 10800, co: 1.78, },
{groupId: "0", id: "br_xl", nm: "br_xl", ct: "br", si: "xl", dw: 183, cap: 1507, count: 2, co: 1.33, },
{groupId: "0", id: "pu_m", nm: "pu_m", ct: "pu", si: "m", dw: 69, cap: 516, count: 1166, co: 0.88, },
{groupId: "0", id: "pu_l", nm: "pu_l", ct: "pu", si: "l", dw: 63, cap: 777, count: 395, co: 0.82, },
{groupId: "0", id: "bu_u", nm: "bu_u", ct: "bu", si: "u", dw: 63, cap: 412, count: 65, co: 0.44, },
{groupId: "0", id: "li_xl", nm: "li_xl", ct: "li", si: "xl", dw: 96, cap: 1228, count: 15, co: 0.4, },
{groupId: "0", id: "li_u", nm: "li_u", ct: "li", si: "u", dw: 36, cap: 319, count: 540, co: 0.43, },
{groupId: "0", id: "bo_l", nm: "bo_l", ct: "bo", si: "l", dw: 65, cap: 344, count: 6, co: 0.52, },
{groupId: "0", id: "bo_xl", nm: "bo_xl", ct: "bo", si: "xl", dw: 88, cap: 796, count: 22, co: 0.65, },
{groupId: "0", id: "bo_u", nm: "bo_u", ct: "bo", si: "u", dw: 31, cap: 443, count: 159, co: 0.3, },
];
var data1 = [
{groupId: "1", parentId: "bd_n", id: "bd_n_ls", nm: "bd_n_ls", ct: "bd", mk: "hu", md: "ls", st: "pr", mt: "c", rf: "yes", si: "n", dw: 18, cap: 224, count: 15, co: 0.24, },
{groupId: "1", parentId: "bd_1", id: "bd_1_ls", nm: "bd_1_ls", ct: "bd", mk: "hu", md: "ls", st: "pr", mt: "c", rf: "yes", si: "1", dw: 24, cap: 456, count: 28, co: 0.18, },
{groupId: "1", parentId: "bd_1", id: "bd_1_sd", nm: "bd_1_sd", ct: "bd", mk: "hu", md: "sd", st: "pr", mt: "c", rf: "yes", si: "1", dw: 24, cap: 327, count: 21, co: 0.16, },
{groupId: "1", parentId: "bd_1", id: "bd_1_sw", nm: "bd_1_sw", ct: "bd", mk: "pa", md: "sw", st: "pr", mt: "c", rf: "yes", si: "1", dw: 22, cap: 339, count: 37, co: 0.19, },
{groupId: "1", parentId: "bd_3", id: "bd_3_di", nm: "bd_3_di", ct: "bd", mk: "wb", md: "di", st: "pr", mt: "c", rf: "yes", si: "3", dw: 25, cap: 643, count: 31, co: 0.18, },
{groupId: "1", parentId: "bd_3", id: "bd_3_pp", nm: "bd_3_pp", ct: "bd", mk: "pa", md: "pp", st: "pr", mt: "c", rf: "yes", si: "3", dw: 28, cap: 471, count: 26, co: 0.35, },
{groupId: "1", parentId: "bd_3", id: "bd_3_sw", nm: "bd_3_sw", ct: "bd", mk: "pa", md: "sw", st: "pr", mt: "c", rf: "yes", si: "3", dw: 24, cap: 515, count: 26, co: 0.24, },
{groupId: "1", parentId: "bd_3", id: "bd_3_ul", nm: "bd_3_ul", ct: "bd", mk: "lv", md: "ul", st: "pr", mt: "c", rf: "yes", si: "3", dw: 25, cap: 406, count: 31, co: 0.15, },
{groupId: "1", parentId: "bd_4", id: "bd_4_bd", nm: "bd_4_bd", ct: "bd", mk: "pa", md: "bd", st: "pr", mt: "c", rf: "yes", si: "4", dw: 27, cap: 439, count: 27, co: NaN, },
{groupId: "1", parentId: "bd_5", id: "bd_5_bd", nm: "bd_5_bd", ct: "bd", mk: "pa", md: "bd", st: "pr", mt: "c", rf: "yes", si: "5", dw: 30, cap: 464, count: 23, co: NaN, },
{groupId: "1", parentId: "bd_5", id: "bd_5_cr", nm: "bd_5_cr", ct: "bd", mk: "pa", md: "cr", st: "pr", mt: "c", rf: "no", si: "5", dw: 32, cap: 592, count: 19, co: NaN, },
{groupId: "1", parentId: "bd_6", id: "bd_6_bd", nm: "bd_6_bd", ct: "bd", mk: "pa", md: "bd", st: "pr", mt: "c", rf: "yes", si: "6", dw: 36, cap: 304, count: 3, co: 0.33, },
{groupId: "1", parentId: "bd_6", id: "bd_6_di", nm: "bd_6_di", ct: "bd", mk: "ho", md: "di", st: "pr", mt: "c", rf: "no", si: "6", dw: 40, cap: 570, count: 20, co: NaN, },
{groupId: "1", parentId: "bd_6", id: "bd_6_di", nm: "bd_6_di", ct: "bd", mk: "sc", md: "di", st: "pr", mt: "c", rf: "yes", si: "6", dw: 37, cap: 512, count: 20, co: 0.24, },
{groupId: "1", parentId: "bd_6", id: "bd_6_on", nm: "bd_6_on", ct: "bd", mk: "hu", md: "on", st: "pr", mt: "c", rf: "yes", si: "6", dw: 47, cap: 598, count: 27, co: 0.45, },
{groupId: "1", parentId: "bd_6", id: "bd_6_sd", nm: "bd_6_sd", ct: "bd", mk: "hu", md: "sd", st: "pr", mt: "c", rf: "yes", si: "6", dw: 34, cap: 568, count: 24, co: 0.29, },
{groupId: "1", parentId: "cpu_4t", id: "cpu_4t_eu", nm: "cpu_4t_eu", ct: "cpu", mk: "pa", md: "eu", st: "pr", mt: "c", rf: "yes", si: "4t", dw: 33, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "cpu_4t", id: "cpu_4t_kub", nm: "cpu_4t_kub", ct: "cpu", mk: "sc", md: "kub", st: "pr", mt: "c", rf: "no", si: "4t", dw: 32, cap: 500, count: 22, co: NaN, },
{groupId: "1", parentId: "cpu_4t", id: "cpu_4t_puld", nm: "cpu_4t_puld", ct: "cpu", mk: "hu", md: "puld", st: "pr", mt: "c", rf: "yes", si: "4t", dw: 38, cap: 207, count: 1, co: NaN, },
{groupId: "1", parentId: "cpu_5t", id: "cpu_5t_kug", nm: "cpu_5t_kug", ct: "cpu", mk: "sc", md: "kug", st: "pr", mt: "c", rf: "no", si: "5t", dw: 34, cap: 563, count: 3, co: NaN, },
{groupId: "1", parentId: "cpu_cl", id: "cpu_cl_b", nm: "cpu_cl_b", ct: "cpu", mk: "gn", md: "b", st: "pr", mt: "c", rf: "yes", si: "cl", dw: 57, cap: 662, count: 10, co: NaN, },
{groupId: "1", parentId: "cpu_cl", id: "cpu_cl_g", nm: "cpu_cl_g", ct: "cpu", mk: "gn", md: "g", st: "pr", mt: "c", rf: "yes", si: "cl", dw: 52, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "cpu_cxl", id: "cpu_cxl_es", nm: "cpu_cxl_es", ct: "cpu", mk: "sc", md: "es", st: "pr", mt: "c", rf: "no", si: "cxl", dw: 51, cap: 734, count: 18, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_atn", nm: "br_m_atn", ct: "br", mk: "tr", md: "atn", st: "md", mt: "p", rf: "no", si: "m", dw: 115, cap: 1080, count: 6, co: 0.73, },
{groupId: "1", parentId: "br_m", id: "br_m_bel", nm: "br_m_bel", ct: "br", mk: "bb", md: "bel", st: "pr", mt: "p", rf: "no", si: "m", dw: 200, cap: 1755, count: 3, co: 2.13, },
{groupId: "1", parentId: "br_m", id: "br_m_bo", nm: "br_m_bo", ct: "br", mk: "re", md: "bo", st: "md", mt: "c", rf: "yes", si: "m", dw: 84, cap: 585, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_bpo", nm: "br_m_bpo", ct: "br", mk: "re", md: "bpo", st: "md", mt: "c", rf: "yes", si: "m", dw: 206, cap: 1852, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_bus", nm: "br_m_bus", ct: "br", mk: "bb", md: "bus", st: "pl", mt: "p", rf: "yes", si: "m", dw: 231, cap: 1427, count: 7, co: 2.67, },
{groupId: "1", parentId: "br_m", id: "br_m_bww", nm: "br_m_bww", ct: "br", mk: "at", md: "bww", st: "md", mt: "p", rf: "no", si: "m", dw: 95, cap: 608, count: 2, co: 0.47, },
{groupId: "1", parentId: "br_m", id: "br_m_byy", nm: "br_m_byy", ct: "br", mk: "un", md: "byy", st: "md", mt: "p", rf: "yes", si: "m", dw: 178, cap: 468, count: 1, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_cb", nm: "br_m_cb", ct: "br", mk: "at", md: "cb", st: "md", mt: "c", rf: "yes", si: "m", dw: 75, cap: 357, count: 2, co: 0.41, },
{groupId: "1", parentId: "br_m", id: "br_m_cl4", nm: "br_m_cl4", ct: "br", mk: "ab", md: "cl4", st: "md", mt: "p", rf: "no", si: "m", dw: 192, cap: 2160, count: 7, co: 1.43, },
{groupId: "1", parentId: "br_m", id: "br_m_clb", nm: "br_m_clb", ct: "br", mk: "bb", md: "clb", st: "pr", mt: "p", rf: "no", si: "m", dw: 166, cap: 896, count: 2, co: 1.91, },
{groupId: "1", parentId: "br_m", id: "br_m_cn", nm: "br_m_cn", ct: "br", mk: "md", md: "cn", st: "pr", mt: "p", rf: "no", si: "m", dw: 154, cap: 1300, count: 4, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_cp", nm: "br_m_cp", ct: "br", mk: "kl", md: "cp", st: "md", mt: "p", rf: "no", si: "m", dw: 212, cap: 0, count: 0, co: 1.14, },
{groupId: "1", parentId: "br_m", id: "br_m_cr", nm: "br_m_cr", ct: "br", mk: "cr", md: "cr", st: "pr", mt: "p", rf: "no", si: "m", dw: 207, cap: 1789, count: 4, co: 1.5, },
{groupId: "1", parentId: "br_m", id: "br_m_cu", nm: "br_m_cu", ct: "br", mk: "au", md: "cu", st: "pr", mt: "m", rf: "mixed", si: "m", dw: 142, cap: 1011, count: 10, co: 1.79, },
{groupId: "1", parentId: "br_m", id: "br_m_db", nm: "br_m_db", ct: "br", mk: "cc", md: "db", st: "md", mt: "c", rf: "yes", si: "m", dw: 64, cap: 541, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_db", nm: "br_m_db", ct: "br", mk: "sl", md: "db", st: "md", mt: "p", rf: "no", si: "m", dw: 84, cap: 507, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_dcbr", nm: "br_m_dcbr", ct: "br", mk: "tn", md: "dcbr", st: "md", mt: "c", rf: "yes", si: "m", dw: 84, cap: 453, count: 1, co: 0.43, },
{groupId: "1", parentId: "br_m", id: "br_m_ec", nm: "br_m_ec", ct: "br", mk: "tr", md: "ec", st: "md", mt: "c", rf: "yes", si: "m", dw: 135, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_fb", nm: "br_m_fb", ct: "br", mk: "ce", md: "fb", st: "md", mt: "c", rf: "yes", si: "m", dw: 90, cap: 825, count: 30, co: 0.5, },
{groupId: "1", parentId: "br_m", id: "br_m_fly", nm: "br_m_fly", ct: "br", mk: "un", md: "fly", st: "md", mt: "p", rf: "no", si: "m", dw: 88, cap: 432, count: 3, co: 0.41, },
{groupId: "1", parentId: "br_m", id: "br_m_gm", nm: "br_m_gm", ct: "br", mk: "fb", md: "gm", st: "pr", mt: "p", rf: "no", si: "m", dw: 215, cap: 365, count: 1, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_iesm", nm: "br_m_iesm", ct: "br", mk: "on", md: "iesm", st: "md", mt: "p", rf: "no", si: "m", dw: 167, cap: 1701, count: 4, co: 1.47, },
{groupId: "1", parentId: "br_m", id: "br_m_ini", nm: "br_m_ini", ct: "br", mk: "rz", md: "ini", st: "pl", mt: "p", rf: "no", si: "m", dw: 222, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_ino", nm: "br_m_ino", ct: "br", mk: "rz", md: "ino", st: "pl", mt: "p", rf: "no", si: "m", dw: 198, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_m10", nm: "br_m_m10", ct: "br", mk: "bd", md: "m10", st: "md", mt: "p", rf: "no", si: "m", dw: 210, cap: 2372, count: 6, co: 1.42, },
{groupId: "1", parentId: "br_m", id: "br_m_mxpg", nm: "br_m_mxpg", ct: "br", mk: "de", md: "mxpg", st: "md", mt: "p", rf: "no", si: "m", dw: 99, cap: 623, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_pan", nm: "br_m_pan", ct: "br", mk: "dd", md: "pan", st: "md", mt: "p", rf: "no", si: "m", dw: 153, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_peb", nm: "br_m_peb", ct: "br", mk: "mo", md: "peb", st: "md", mt: "c", rf: "yes", si: "m", dw: 93, cap: 605, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_pr", nm: "br_m_pr", ct: "br", mk: "rz", md: "pr", st: "pr", mt: "p", rf: "no", si: "m", dw: 226, cap: 1845, count: 1, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_pr2", nm: "br_m_pr2", ct: "br", mk: "ab", md: "pr2", st: "md", mt: "c", rf: "yes", si: "m", dw: 118, cap: 885, count: 5, co: 1.18, },
{groupId: "1", parentId: "br_m", id: "br_m_pr3", nm: "br_m_pr3", ct: "br", mk: "ab", md: "pr3", st: "md", mt: "c", rf: "yes", si: "m", dw: 139, cap: 1683, count: 22, co: 1.09, },
{groupId: "1", parentId: "br_m", id: "br_m_pr4", nm: "br_m_pr4", ct: "br", mk: "ab", md: "pr4", st: "md", mt: "c", rf: "yes", si: "m", dw: 175, cap: 2204, count: 40, co: 1.5, },
{groupId: "1", parentId: "br_m", id: "br_m_psb", nm: "br_m_psb", ct: "br", mk: "mo", md: "psb", st: "md", mt: "c", rf: "yes", si: "m", dw: 116, cap: 837, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_reb", nm: "br_m_reb", ct: "br", mk: "rz", md: "reb", st: "pr", mt: "p", rf: "no", si: "m", dw: 205, cap: 1170, count: 2, co: 1.7, },
{groupId: "1", parentId: "br_m", id: "br_m_sb", nm: "br_m_sb", ct: "br", mk: "sl", md: "sb", st: "md", mt: "c", rf: "yes", si: "m", dw: 78, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_sb", nm: "br_m_sb", ct: "br", mk: "tn", md: "sb", st: "md", mt: "c", rf: "yes", si: "m", dw: 109, cap: 738, count: 3, co: 0.89, },
{groupId: "1", parentId: "br_m", id: "br_m_sc", nm: "br_m_sc", ct: "br", mk: "tr", md: "sc", st: "md", mt: "c", rf: "yes", si: "m", dw: 93, cap: 477, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_sed", nm: "br_m_sed", ct: "br", mk: "rz", md: "sed", st: "pl", mt: "p", rf: "no", si: "m", dw: 226, cap: 1468, count: 2, co: 2.52, },
{groupId: "1", parentId: "br_m", id: "br_m_sim", nm: "br_m_sim", ct: "br", mk: "cv", md: "sim", st: "md", mt: "p", rf: "no", si: "m", dw: 61, cap: 360, count: 1, co: 0.43, },
{groupId: "1", parentId: "br_m", id: "br_m_slbb", nm: "br_m_slbb", ct: "br", mk: "tr", md: "slbb", st: "md", mt: "c", rf: "yes", si: "m", dw: 95, cap: 477, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_slmx", nm: "br_m_slmx", ct: "br", mk: "mo", md: "slmx", st: "md", mt: "p", rf: "no", si: "m", dw: 173, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_slmx", nm: "br_m_slmx", ct: "br", mk: "tn", md: "slmx", st: "md", mt: "p", rf: "no", si: "m", dw: 147, cap: 1457, count: 1, co: 1.15, },
{groupId: "1", parentId: "br_m", id: "br_m_slob", nm: "br_m_slob", ct: "br", mk: "tr", md: "slob", st: "md", mt: "p", rf: "no", si: "m", dw: 92, cap: 1139, count: 3, co: 0.88, },
{groupId: "1", parentId: "br_m", id: "br_m_sn", nm: "br_m_sn", ct: "br", mk: "md", md: "sn", st: "pr", mt: "p", rf: "no", si: "m", dw: 152, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_sn", nm: "br_m_sn", ct: "br", mk: "tk", md: "sn", st: "pr", mt: "p", rf: "no", si: "m", dw: 132, cap: 1526, count: 3, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_ss", nm: "br_m_ss", ct: "br", mk: "au", md: "ss", st: "pr", mt: "p", rf: "no", si: "m", dw: 160, cap: 1430, count: 3, co: 1.79, },
{groupId: "1", parentId: "br_m", id: "br_m_ss", nm: "br_m_ss", ct: "br", mk: "bs", md: "ss", st: "md", mt: "p", rf: "no", si: "m", dw: 173, cap: 1767, count: 1, co: 0.99, },
{groupId: "1", parentId: "br_m", id: "br_m_suqu", nm: "br_m_suqu", ct: "br", mk: "se", md: "suqu", st: "md", mt: "c", rf: "yes", si: "m", dw: 181, cap: 1280, count: 1, co: 1.18, },
{groupId: "1", parentId: "br_m", id: "br_m_td", nm: "br_m_td", ct: "br", mk: "bb", md: "td", st: "pr", mt: "p", rf: "no", si: "m", dw: 164, cap: 0, count: 0, co: 1.65, },
{groupId: "1", parentId: "br_m", id: "br_m_ub", nm: "br_m_ub", ct: "br", mk: "tn", md: "ub", st: "md", mt: "c", rf: "yes", si: "m", dw: 95, cap: 853, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_usb", nm: "br_m_usb", ct: "br", mk: "tn", md: "usb", st: "md", mt: "c", rf: "yes", si: "m", dw: 98, cap: 679, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_wcpb", nm: "br_m_wcpb", ct: "br", mk: "cv", md: "wcpb", st: "md", mt: "p", rf: "no", si: "m", dw: 88, cap: 770, count: 6, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_wcpbw", nm: "br_m_wcpbw", ct: "br", mk: "cv", md: "wcpbw", st: "md", mt: "p", rf: "no", si: "m", dw: 77, cap: 284, count: 2, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_wibq", nm: "br_m_wibq", ct: "br", mk: "cv", md: "wibq", st: "md", mt: "c", rf: "yes", si: "m", dw: 81, cap: 122, count: 1, co: 0.47, },
{groupId: "1", parentId: "br_m", id: "br_m_wpqab", nm: "br_m_wpqab", ct: "br", mk: "cv", md: "wpqab", st: "md", mt: "c", rf: "yes", si: "m", dw: 84, cap: 977, count: 7, co: NaN, },
{groupId: "1", parentId: "br_m", id: "br_m_xp", nm: "br_m_xp", ct: "br", mk: "fc", md: "xp", st: "pl", mt: "p", rf: "no", si: "m", dw: 195, cap: 1207, count: 2, co: 0.88, },
{groupId: "1", parentId: "br_m", id: "br_m_yn", nm: "br_m_yn", ct: "br", mk: "md", md: "yn", st: "pr", mt: "p", rf: "no", si: "m", dw: 163, cap: 1412, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_24", nm: "br_l_24", ct: "br", mk: "cd", md: "24", st: "pl", mt: "p", rf: "no", si: "l", dw: 226, cap: 2083, count: 16, co: 1.58, },
{groupId: "1", parentId: "br_l", id: "br_l_abd", nm: "br_l_abd", ct: "br", mk: "cz", md: "abd", st: "pr", mt: "p", rf: "no", si: "l", dw: 205, cap: 1688, count: 4, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_an", nm: "br_l_an", ct: "br", mk: "cz", md: "an", st: "pr", mt: "p", rf: "no", si: "l", dw: 224, cap: 0, count: 0, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_aq", nm: "br_l_aq", ct: "br", mk: "cr", md: "aq", st: "pr", mt: "p", rf: "no", si: "l", dw: 228, cap: 2097, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_asb", nm: "br_l_asb", ct: "br", mk: "pr", md: "asb", st: "md", mt: "c", rf: "no", si: "l", dw: 100, cap: 984, count: 5, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_bb", nm: "br_l_bb", ct: "br", mk: "rz", md: "bb", st: "pr", mt: "p", rf: "no", si: "l", dw: 239, cap: 1939, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_by", nm: "br_l_by", ct: "br", mk: "rz", md: "by", st: "pr", mt: "p", rf: "yes", si: "l", dw: 225, cap: 2426, count: 4, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_cl4", nm: "br_l_cl4", ct: "br", mk: "ab", md: "cl4", st: "md", mt: "p", rf: "no", si: "l", dw: 207, cap: 2525, count: 13, co: 1.28, },
{groupId: "1", parentId: "br_l", id: "br_l_cr", nm: "br_l_cr", ct: "br", mk: "cr", md: "cr", st: "pr", mt: "p", rf: "no", si: "l", dw: 226, cap: 2157, count: 13, co: 1.67, },
{groupId: "1", parentId: "br_l", id: "br_l_cu", nm: "br_l_cu", ct: "br", mk: "au", md: "cu", st: "pr", mt: "m", rf: "mixed", si: "l", dw: 174, cap: 1258, count: 8, co: 1.79, },
{groupId: "1", parentId: "br_l", id: "br_l_db", nm: "br_l_db", ct: "br", mk: "cc", md: "db", st: "md", mt: "c", rf: "yes", si: "l", dw: 74, cap: 510, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_db", nm: "br_l_db", ct: "br", mk: "sl", md: "db", st: "md", mt: "p", rf: "no", si: "l", dw: 99, cap: 552, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_df2", nm: "br_l_df2", ct: "br", mk: "ab", md: "df2", st: "md", mt: "c", rf: "yes", si: "l", dw: 147, cap: 1379, count: 5, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_df3", nm: "br_l_df3", ct: "br", mk: "ab", md: "df3", st: "md", mt: "c", rf: "yes", si: "l", dw: 166, cap: 1486, count: 3, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_ec", nm: "br_l_ec", ct: "br", mk: "tr", md: "ec", st: "md", mt: "c", rf: "yes", si: "l", dw: 160, cap: 400, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_frb", nm: "br_l_frb", ct: "br", mk: "ml", md: "frb", st: "md", mt: "c", rf: "yes", si: "l", dw: 95, cap: 647, count: 14, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_frub", nm: "br_l_frub", ct: "br", mk: "ml", md: "frub", st: "md", mt: "c", rf: "no", si: "l", dw: 89, cap: 916, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_id", nm: "br_l_id", ct: "br", mk: "dc", md: "id", st: "pr", mt: "p", rf: "no", si: "l", dw: 224, cap: 1335, count: 1, co: 1.7, },
{groupId: "1", parentId: "br_l", id: "br_l_iesm", nm: "br_l_iesm", ct: "br", mk: "on", md: "iesm", st: "md", mt: "p", rf: "no", si: "l", dw: 178, cap: 1734, count: 2, co: 1.57, },
{groupId: "1", parentId: "br_l", id: "br_l_ini", nm: "br_l_ini", ct: "br", mk: "rz", md: "ini", st: "pl", mt: "p", rf: "no", si: "l", dw: 229, cap: 1939, count: 11, co: 2.16, },
{groupId: "1", parentId: "br_l", id: "br_l_ino", nm: "br_l_ino", ct: "br", mk: "rz", md: "ino", st: "pl", mt: "p", rf: "no", si: "l", dw: 202, cap: 2294, count: 12, co: 1.73, },
{groupId: "1", parentId: "br_l", id: "br_l_ins", nm: "br_l_ins", ct: "br", mk: "rz", md: "ins", st: "pl", mt: "p", rf: "no", si: "l", dw: 207, cap: 1485, count: 10, co: 1.81, },
{groupId: "1", parentId: "br_l", id: "br_l_lm", nm: "br_l_lm", ct: "br", mk: "rz", md: "lm", st: "pr", mt: "p", rf: "no", si: "l", dw: 199, cap: 658, count: 1, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_mag", nm: "br_l_mag", ct: "br", mk: "bb", md: "mag", st: "pr", mt: "p", rf: "yes", si: "l", dw: 241, cap: 2103, count: 2, co: 3.33, },
{groupId: "1", parentId: "br_l", id: "br_l_nc", nm: "br_l_nc", ct: "br", mk: "es", md: "nc", st: "md", mt: "c", rf: "no", si: "l", dw: 208, cap: 1668, count: 1, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_np", nm: "br_l_np", ct: "br", mk: "cz", md: "np", st: "pr", mt: "p", rf: "no", si: "l", dw: 173, cap: 1505, count: 1, co: 2.19, },
{groupId: "1", parentId: "br_l", id: "br_l_pd", nm: "br_l_pd", ct: "br", mk: "nr", md: "pd", st: "pr", mt: "c", rf: "yes", si: "l", dw: 164, cap: 1276, count: 2, co: 2.25, },
{groupId: "1", parentId: "br_l", id: "br_l_pr", nm: "br_l_pr", ct: "br", mk: "au", md: "pr", st: "pr", mt: "p", rf: "no", si: "l", dw: 173, cap: 652, count: 2, co: 1.36, },
{groupId: "1", parentId: "br_l", id: "br_l_pwt", nm: "br_l_pwt", ct: "br", mk: "de", md: "pwt", st: "md", mt: "c", rf: "yes", si: "l", dw: 101, cap: 1024, count: 14, co: 0.81, },
{groupId: "1", parentId: "br_l", id: "br_l_reb", nm: "br_l_reb", ct: "br", mk: "rz", md: "reb", st: "pr", mt: "p", rf: "no", si: "l", dw: 200, cap: 1331, count: 2, co: 1.82, },
{groupId: "1", parentId: "br_l", id: "br_l_sb", nm: "br_l_sb", ct: "br", mk: "ns", md: "sb", st: "md", mt: "p", rf: "no", si: "l", dw: 242, cap: 1581, count: 12, co: 1.44, },
{groupId: "1", parentId: "br_l", id: "br_l_sb", nm: "br_l_sb", ct: "br", mk: "sl", md: "sb", st: "md", mt: "c", rf: "yes", si: "l", dw: 88, cap: 881, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_sc", nm: "br_l_sc", ct: "br", mk: "tr", md: "sc", st: "md", mt: "c", rf: "yes", si: "l", dw: 115, cap: 666, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_sd", nm: "br_l_sd", ct: "br", mk: "au", md: "sd", st: "pr", mt: "p", rf: "no", si: "l", dw: 189, cap: 895, count: 13, co: 1.69, },
{groupId: "1", parentId: "br_l", id: "br_l_sf", nm: "br_l_sf", ct: "br", mk: "rz", md: "sf", st: "pr", mt: "p", rf: "no", si: "l", dw: 235, cap: 1876, count: 11, co: 2.36, },
{groupId: "1", parentId: "br_l", id: "br_l_sl", nm: "br_l_sl", ct: "br", mk: "ns", md: "sl", st: "md", mt: "p", rf: "no", si: "l", dw: 168, cap: 1154, count: 2, co: 1.24, },
{groupId: "1", parentId: "br_l", id: "br_l_slbb", nm: "br_l_slbb", ct: "br", mk: "tr", md: "slbb", st: "md", mt: "c", rf: "yes", si: "l", dw: 108, cap: 559, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_slmx", nm: "br_l_slmx", ct: "br", mk: "mo", md: "slmx", st: "md", mt: "p", rf: "no", si: "l", dw: 189, cap: 1409, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_slum", nm: "br_l_slum", ct: "br", mk: "tn", md: "slum", st: "md", mt: "p", rf: "no", si: "l", dw: 185, cap: 1754, count: 12, co: 1.82, },
{groupId: "1", parentId: "br_l", id: "br_l_sup", nm: "br_l_sup", ct: "br", mk: "wl", md: "sup", st: "pl", mt: "p", rf: "no", si: "l", dw: 151, cap: 1317, count: 12, co: 1.48, },
{groupId: "1", parentId: "br_l", id: "br_l_td", nm: "br_l_td", ct: "br", mk: "bb", md: "td", st: "pr", mt: "p", rf: "no", si: "l", dw: 184, cap: 1190, count: 7, co: 2.01, },
{groupId: "1", parentId: "br_l", id: "br_l_ul", nm: "br_l_ul", ct: "br", mk: "md", md: "ul", st: "pr", mt: "p", rf: "no", si: "l", dw: 199, cap: 2038, count: 2, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_uts", nm: "br_l_uts", ct: "br", mk: "fs", md: "uts", st: "pr", mt: "p", rf: "no", si: "l", dw: 232, cap: 2524, count: 5, co: NaN, },
{groupId: "1", parentId: "br_l", id: "br_l_yn", nm: "br_l_yn", ct: "br", mk: "md", md: "yn", st: "pr", mt: "p", rf: "no", si: "l", dw: 169, cap: 1121, count: 2, co: NaN, },
{groupId: "1", parentId: "br_xl", id: "br_xl_sl", nm: "br_xl_sl", ct: "br", mk: "ns", md: "sl", st: "md", mt: "p", rf: "no", si: "xl", dw: 183, cap: 1507, count: 2, co: 1.33, },
{groupId: "1", parentId: "pu_m", id: "pu_m_afpu3", nm: "pu_m_afpu3", ct: "pu", mk: "ab", md: "afpu3", st: "md", mt: "c", rf: "yes", si: "m", dw: 106, cap: 354, count: 2, co: 1.18, },
{groupId: "1", parentId: "pu_m", id: "pu_m_au", nm: "pu_m_au", ct: "pu", mk: "at", md: "au", st: "pl", mt: "c", rf: "yes", si: "m", dw: 54, cap: 295, count: 2, co: 0.59, },
{groupId: "1", parentId: "pu_m", id: "pu_m_au", nm: "pu_m_au", ct: "pu", mk: "de", md: "au", st: "pl", mt: "c", rf: "yes", si: "m", dw: 76, cap: 655, count: 2, co: 0.67, },
{groupId: "1", parentId: "pu_m", id: "pu_m_dcpu", nm: "pu_m_dcpu", ct: "pu", mk: "tn", md: "dcpu", st: "pl", mt: "c", rf: "yes", si: "m", dw: 55, cap: 426, count: 1, co: 0.54, },
{groupId: "1", parentId: "pu_m", id: "pu_m_dmxu", nm: "pu_m_dmxu", ct: "pu", mk: "re", md: "dmxu", st: "pl", mt: "c", rf: "yes", si: "m", dw: 59, cap: 787, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_eapu", nm: "pu_m_eapu", ct: "pu", mk: "tn", md: "eapu", st: "pl", mt: "c", rf: "yes", si: "m", dw: 72, cap: 490, count: 3, co: 1.04, },
{groupId: "1", parentId: "pu_m", id: "pu_m_ff", nm: "pu_m_ff", ct: "pu", mk: "de", md: "ff", st: "pl", mt: "c", rf: "yes", si: "m", dw: 67, cap: 553, count: 3, co: 0.56, },
{groupId: "1", parentId: "pu_m", id: "pu_m_ffcc", nm: "pu_m_ffcc", ct: "pu", mk: "de", md: "ffcc", st: "pl", mt: "c", rf: "yes", si: "m", dw: 55, cap: 641, count: 1, co: 0.92, },
{groupId: "1", parentId: "pu_m", id: "pu_m_fm", nm: "pu_m_fm", ct: "pu", mk: "tn", md: "fm", st: "pl", mt: "c", rf: "yes", si: "m", dw: 81, cap: 499, count: 1, co: 0.78, },
{groupId: "1", parentId: "pu_m", id: "pu_m_frou", nm: "pu_m_frou", ct: "pu", mk: "re", md: "frou", st: "pl", mt: "c", rf: "yes", si: "m", dw: 65, cap: 205, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_fw", nm: "pu_m_fw", ct: "pu", mk: "tn", md: "fw", st: "pl", mt: "c", rf: "yes", si: "m", dw: 78, cap: 705, count: 1, co: 1.01, },
{groupId: "1", parentId: "pu_m", id: "pu_m_mu", nm: "pu_m_mu", ct: "pu", mk: "mo", md: "mu", st: "md", mt: "c", rf: "yes", si: "m", dw: 78, cap: 482, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_mu", nm: "pu_m_mu", ct: "pu", mk: "re", md: "mu", st: "pl", mt: "c", rf: "yes", si: "m", dw: 43, cap: 318, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_mxum", nm: "pu_m_mxum", ct: "pu", mk: "de", md: "mxum", st: "pl", mt: "c", rf: "yes", si: "m", dw: 51, cap: 381, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_mxum", nm: "pu_m_mxum", ct: "pu", mk: "re", md: "mxum", st: "pl", mt: "c", rf: "yes", si: "m", dw: 61, cap: 409, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_pdpu", nm: "pu_m_pdpu", ct: "pu", mk: "tr", md: "pdpu", st: "md", mt: "c", rf: "yes", si: "m", dw: 81, cap: 615, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_popu", nm: "pu_m_popu", ct: "pu", mk: "tr", md: "popu", st: "md", mt: "c", rf: "yes", si: "m", dw: 84, cap: 981, count: 3, co: 1.04, },
{groupId: "1", parentId: "pu_m", id: "pu_m_pu3", nm: "pu_m_pu3", ct: "pu", mk: "ab", md: "pu3", st: "md", mt: "c", rf: "yes", si: "m", dw: 110, cap: 729, count: 1, co: 1.13, },
{groupId: "1", parentId: "pu_m", id: "pu_m_pum", nm: "pu_m_pum", ct: "pu", mk: "un", md: "pum", st: "md", mt: "c", rf: "yes", si: "m", dw: 44, cap: 473, count: 3, co: NaN, },
{groupId: "1", parentId: "pu_m", id: "pu_m_puw", nm: "pu_m_puw", ct: "pu", mk: "de", md: "puw", st: "pl", mt: "c", rf: "yes", si: "m", dw: 53, cap: 353, count: 1, co: 0.9, },
{groupId: "1", parentId: "pu_m", id: "pu_m_rf", nm: "pu_m_rf", ct: "pu", mk: "de", md: "rf", st: "pl", mt: "c", rf: "yes", si: "m", dw: 73, cap: 671, count: 13, co: 1.04, },
{groupId: "1", parentId: "pu_m", id: "pu_m_spum", nm: "pu_m_spum", ct: "pu", mk: "tn", md: "spum", st: "pl", mt: "c", rf: "yes", si: "m", dw: 75, cap: 347, count: 2, co: NaN, },
{groupId: "1", parentId: "pu_l", id: "pu_l_diunmx", nm: "pu_l_diunmx", ct: "pu", mk: "al", md: "diunmx", st: "pl", mt: "c", rf: "yes", si: "l", dw: 55, cap: 494, count: 16, co: 0.68, },
{groupId: "1", parentId: "pu_l", id: "pu_l_ff", nm: "pu_l_ff", ct: "pu", mk: "de", md: "ff", st: "pl", mt: "c", rf: "no", si: "l", dw: 54, cap: 724, count: 25, co: NaN, },
{groupId: "1", parentId: "pu_l", id: "pu_l_ff?", nm: "pu_l_ff?", ct: "pu", mk: "de", md: "ff?", st: "pl", mt: "c", rf: "yes", si: "l", dw: 75, cap: 1038, count: 3, co: 0.65, },
{groupId: "1", parentId: "pu_l", id: "pu_l_rf", nm: "pu_l_rf", ct: "pu", mk: "de", md: "rf", st: "pl", mt: "c", rf: "yes", si: "l", dw: 68, cap: 1134, count: 25, co: NaN, },
{groupId: "1", parentId: "pu_l", id: "pu_l_silmx", nm: "pu_l_silmx", ct: "pu", mk: "de", md: "silmx", st: "pl", mt: "c", rf: "yes", si: "l", dw: 66, cap: 497, count: 10, co: 1.13, },
{groupId: "1", parentId: "bu_u", id: "bu_u_bu", nm: "bu_u_bu", ct: "bu", mk: "at", md: "bu", st: "pl", mt: "p", rf: "no", si: "u", dw: 47, cap: 265, count: 2, co: 0.36, },
{groupId: "1", parentId: "bu_u", id: "bu_u_bu", nm: "bu_u_bu", ct: "bu", mk: "di", md: "bu", st: "pl", mt: "p", rf: "no", si: "u", dw: 86, cap: 707, count: 2, co: 0.53, },
{groupId: "1", parentId: "bu_u", id: "bu_u_bu", nm: "bu_u_bu", ct: "bu", mk: "tr", md: "bu", st: "pl", mt: "p", rf: "no", si: "u", dw: 65, cap: 232, count: 2, co: NaN, },
{groupId: "1", parentId: "bu_u", id: "bu_u_bubl", nm: "bu_u_bubl", ct: "bu", mk: "un", md: "bubl", st: "pl", mt: "c", rf: "yes", si: "u", dw: 58, cap: 445, count: 5, co: NaN, },
{groupId: "1", parentId: "bu_u", id: "bu_u_etu", nm: "bu_u_etu", ct: "bu", mk: "re", md: "etu", st: "pl", mt: "p", rf: "no", si: "u", dw: 59, cap: 415, count: 2, co: NaN, },
{groupId: "1", parentId: "li_xl", id: "li_xl_chp", nm: "li_xl_chp", ct: "li", mk: "rz", md: "chp", st: "pl", mt: "p", rf: "no", si: "xl", dw: 96, cap: 1228, count: 15, co: 0.4, },
{groupId: "1", parentId: "li_u", id: "li_u_al", nm: "li_u_al", ct: "li", mk: "tr", md: "al", st: "pl", mt: "p", rf: "no", si: "u", dw: 60, cap: 503, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_gfm", nm: "li_u_gfm", ct: "li", mk: "re", md: "gfm", st: "pl", mt: "p", rf: "no", si: "u", dw: 27, cap: 114, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_liaphr", nm: "li_u_liaphr", ct: "li", mk: "tr", md: "liaphr", st: "md", mt: "p", rf: "no", si: "u", dw: 84, cap: 821, count: 3, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_liblhr", nm: "li_u_liblhr", ct: "li", mk: "un", md: "liblhr", st: "md", mt: "p", rf: "no", si: "u", dw: 89, cap: 587, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_lifr", nm: "li_u_lifr", ct: "li", mk: "un", md: "lifr", st: "pl", mt: "p", rf: "no", si: "u", dw: 25, cap: 299, count: 23, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_mg", nm: "li_u_mg", ct: "li", mk: "at", md: "mg", st: "pl", mt: "p", rf: "no", si: "u", dw: 9, cap: 85, count: 2, co: 0.43, },
{groupId: "1", parentId: "li_u", id: "li_u_mg", nm: "li_u_mg", ct: "li", mk: "de", md: "mg", st: "pl", mt: "p", rf: "no", si: "u", dw: 22, cap: 266, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_mgm", nm: "li_u_mgm", ct: "li", mk: "tn", md: "mgm", st: "pl", mt: "p", rf: "no", si: "u", dw: 21, cap: 268, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_mp", nm: "li_u_mp", ct: "li", mk: "cp", md: "mp", st: "pl", mt: "p", rf: "no", si: "u", dw: 16, cap: 259, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_pop", nm: "li_u_pop", ct: "li", mk: "re", md: "pop", st: "pl", mt: "p", rf: "no", si: "u", dw: 44, cap: 482, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_sfm", nm: "li_u_sfm", ct: "li", mk: "de", md: "sfm", st: "pl", mt: "p", rf: "no", si: "u", dw: 5, cap: 41, count: 2, co: NaN, },
{groupId: "1", parentId: "li_u", id: "li_u_sop", nm: "li_u_sop", ct: "li", mk: "tn", md: "sop", st: "pl", mt: "p", rf: "no", si: "u", dw: 38, cap: 105, count: 1, co: NaN, },
{groupId: "1", parentId: "bo_l", id: "bo_l_almx", nm: "bo_l_almx", ct: "bo", mk: "ab", md: "almx", st: "pl", mt: "c", rf: "yes", si: "l", dw: 65, cap: 344, count: 6, co: 0.52, },
{groupId: "1", parentId: "bo_xl", id: "bo_xl_tlb", nm: "bo_xl_tlb", ct: "bo", mk: "tr", md: "tlb", st: "pl", mt: "c", rf: "yes", si: "xl", dw: 88, cap: 796, count: 22, co: 0.65, },
{groupId: "1", parentId: "bo_u", id: "bo_u_bodi", nm: "bo_u_bodi", ct: "bo", mk: "un", md: "bodi", st: "pl", mt: "c", rf: "yes", si: "u", dw: 21, cap: 309, count: 7, co: NaN, },
{groupId: "1", parentId: "bo_u", id: "bo_u_boplw18", nm: "bo_u_boplw18", ct: "bo", mk: "un", md: "boplw18", st: "pl", mt: "c", rf: "yes", si: "u", dw: 51, cap: 527, count: 5, co: NaN, },
{groupId: "1", parentId: "bo_u", id: "bo_u_tlb12", nm: "bo_u_tlb12", ct: "bo", mk: "tr", md: "tlb12", st: "pl", mt: "c", rf: "yes", si: "u", dw: 22, cap: 495, count: 41, co: 0.3, },
];